plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-admin
  - kramdown-parser-gfm
  - jekyll-redirect-from

encoding: UTF-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

name: Michael Lamb
title: Michael Lamb
brand: Michael Lamb
description: A tech & life blog written and maintained by Michael Lamb
url: 'https://blog.michaellamb.dev'
email: michael@michaellamb.dev
author: Michael Lamb
image: /seo/default.png

future: true

permalink: '/:year/:month/:title/'
extensions:
  - .html

exclude:
  - README.md
  - version.txt
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _templates/

favicon:
  enabled: true
  local:
    enabled: true
    partial_url: /img/favicon.png
    type: png

rss:
  enabled: true
  managing_editor:
    enabled: true
    managing_editor: michael@michaellamb.dev (Michael Lamb)
  webmaster:
    enabled: true
    webmaster: michael@michaellamb.dev (Michael Lamb)
  ttl:
    enabled: true
    ttl: 300
  image:
    enabled: 'true'
    image: seo/default.png
